name: learning_curve_academy
description: Lets Learn Together


environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 
  assets:
    - assets/brand.png
    - assets/logo.png
    - assets/banner.png
    - assets/icons/bookshelf.png
    - assets/icons/cube.png
    - assets/icons/pastquestion.png
    - assets/icons/sample.png
    - assets/icons/units.png
    - assets/icons/course_works.png
    - assets/icons/arrow.png
    - assets/icons/checkmark.png
    - assets/icons/dualarrow.png
    - assets/set1/
    - assets/set2/
    - assets/set3/
    - assets/set4/
    - assets/set5/


