name: learning_curve_academy
description: Lets Learn Together


environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand.png
    - assets/logo.png
    - assets/banner.png
    - assets/icons/bookshelf.png
    - assets/icons/cube.png
    - assets/icons/pastquestion.png
    - assets/icons/sample.png
    - assets/icons/units.png
    - assets/icons/course_works.png


